version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: deadline-mysql
    restart: always

    ports:
      - "3308:3306"

    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql